# -*- coding: utf-8 -*-
"""case study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QhuwCW7tfAGeIoIxoPA3FMwKC6zg3it-
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
gracy=pd.read_csv('energy.csv')
print(gracy)
srh=gracy[gracy['State']=='Andhra']
rcb=gracy[gracy['State']=='Karnataka']
fig,diag=plt.subplots(2)
diag[0].plot(srh['Date'],srh['Consumption'],color='red')
diag[1].plot(rcb['Date'],rcb['Consumption'],color='Purple')
srh=gracy[gracy['State']=='Telengana']
rcb=gracy[gracy['State']=='Tripura']
fig,diag=plt.subplots(2)
diag[0].bar(srh['Date'],srh['Consumption'],color='red')
diag[1].bar(rcb['Date'],rcb['Consumption'],color='Purple')
cse4='Kerala'
cse5='Delhi'
tdp=[cse4,cse5]
srh=gracy[gracy['State']=='Kerala']['Consumption'].sum()
rcb=gracy[gracy['State']=='Delhi']['Consumption'].sum()
ysr=[srh,rcb]
fig,diag=plt.subplots(2)
diag[0].pie(ysr,labels=tdp)

import pandas as mm
import matplotlib.pyplot as ss
import seaborn as cse
ntr=mm.read_csv('heart.csv')
print(ntr)
cse.scatterplot(x='age',y='bp',data=ntr,hue='gender')
ss.title('heart attack')
ss.xlabel('age')
ss.ylabel('bp')
ss.show()

cse.lineplot(x='age',y='cholestrol',data=ntr)
ss.show()

cse.boxplot(x='target',y='value',data=ntr)
ss.show()

color=['red','yellow']
cse.countplot(x='target',data=ntr,palette=color)
ss.show()